version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: debug.Dockerfile
    volumes:
      - ${PWD}:/src-root
    environment:
      RUST_LOG: info
      DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@127.0.0.1:3306/${MYSQL_DB}
      REDIS_URL: redis://cache:6379/
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - 3000:3000
    depends_on:
      - db
      - cache
    restart: always
  
  db:
    image: mysql:8.0.22
    ports:
      - 3306:3306
    volumes:
      - /home/sl/mysql/data:/var/lib/mysql/data
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}
    restart: always

  cache:
    image: redis:6.0.9
    ports:
      - 6379:6379
    restart: always
