# http test

# GET http://localhost:3000/status

# GET http://localhost:3000/api/v1/cosmetics/brands

# GET http://localhost:3000/api/v1/cosmetics/brand/1

# GET http://localhost:3000/api/v1/cosmetics/product/1




# ADMIN

# POST http://localhost:3000/api/v1/cosmetics/brands
# [
#     {
#         "name": "brand apple"
#     },
#     {
#         "name": "brand banana"
#     },
#     {
#         "name": "brand grape"
#     },
#     {
#         "name": "brand tangerine"
#     },
#     {
#         "name": "brand orange"
#     }
# ]

# GET http://localhost:3000/api/v1/cosmetics/brands

# PUT http://localhost:3000/api/v1/cosmetics/brands/sequence
# [
#     {"id": 1, "sequence": 10},
#     {"id": 2, "sequence": 20},
#     {"id": 3, "sequence": 30},
#     {"id": 4, "sequence": 40},
#     {"id": 5, "sequence": 50}
# ]

# DELETE http://localhost:3000/api/v1/cosmetics/brand/1



# POST http://localhost:3000/api/v1/cosmetics/product
# {
#      "name":"good apple",
#      "alias":"apple",
#      "title":"apple1",
#      "subtitle":"apple one",
#      "brand_id": 1,
#      "brand_name":"",
#      "sell_price": 12.34,
#      "img_url":"http://www.xxx.com"
# }

# GET http://localhost:3000/api/v1/cosmetics/products

# GET http://localhost:3000/api/v1/cosmetics/product/2

# PUT http://localhost:3000/api/v1/cosmetics/product/2
# {
#      "name":"banana",
#      "alias":"ba",
#      "title":"good banana",
#      "subtitle":"good banana for sell",
#      "brand_id": 2,
#      "brand_name":"brand banana",
#      "sell_price": 12.34,
#      "img_url":"http://www.xxx.com"
# }

DELETE http://localhost:3000/api/v1/cosmetics/product/2



# POST http://localhost:3000/api/v1/cosmetics/product/hot
# [1, 2, 3, 4, 8]

# GET http://localhost:3000/api/v1/cosmetics/product/hot
