CREATE TABLE `price_history` (
  `id` BIGINT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `product_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '品牌 product.id',
  `sell_price` DECIMAL(9,2) NOT NULL DEFAULT 0 COMMENT '售价',
  `import_price` DECIMAL(9,2) NOT NULL DEFAULT 0 COMMENT '参考进货价',
  `price_time` DATETIME NOT NULL COMMENT '价格时间',
  `status` TINYINT NOT NULL DEFAULT 0 COMMENT '状态，0：默认，1：已删除',
  `creator` VARCHAR(32) NOT NULL DEFAULT '',
  `modifier` VARCHAR(32) NOT NULL DEFAULT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY `idx_pid` (`product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商品价格历史表';
